write(50,*) "On branch cursor/align-gauss-constraint-implementation-with-paper-claude-4.5-opus-high-thinking-4441"
write(50,*) "Your branch is up to date with 'origin/cursor/align-gauss-constraint-implementation-with-paper-claude-4.5-opus-high-thinking-4441'."
write(50,*) ""
write(50,*) "Changes not staged for commit:"
write(50,*) "  (use ""git add <file>..."" to update what will be committed)"
write(50,*) "  (use ""git restore <file>..."" to discard changes in working directory)"
write(50,*) "	modified:   ../Documentation/Z2_Strict_Gauss_Constraint.md"
write(50,*) "	modified:   ALF.out"
write(50,*) "	modified:   Hamiltonians/Hamiltonian_Z2_Matter_smod.F90"
write(50,*) "	modified:   Hamiltonians/Hamiltonian_Z2_Matter_smod.o"
write(50,*) "	modified:   control_mod.o"
write(50,*) "	modified:   git.h"
write(50,*) "	modified:   git_status.h"
write(50,*) "	modified:   main.F90"
write(50,*) "	modified:   main.o"
write(50,*) "	modified:   ../test_gauss_clean/Den_eq"
write(50,*) "	modified:   ../test_gauss_clean/Flux_scal"
write(50,*) "	modified:   ../test_gauss_clean/GaussViol_scal"
write(50,*) "	modified:   ../test_gauss_clean/Gauss_scal"
write(50,*) "	modified:   ../test_gauss_clean/Green_eq"
write(50,*) "	modified:   ../test_gauss_clean/Greenf_eq"
write(50,*) "	modified:   ../test_gauss_clean/Part_scal"
write(50,*) "	modified:   ../test_gauss_clean/Q_eq"
write(50,*) "	modified:   ../test_gauss_clean/Q_scal"
write(50,*) "	modified:   ../test_gauss_clean/SpinZ_eq"
write(50,*) "	modified:   ../test_gauss_clean/X_scal"
write(50,*) "	modified:   ../test_gauss_clean/confout_0"
write(50,*) "	modified:   ../test_gauss_clean/info"
write(50,*) "	modified:   ../test_gauss_clean/info_git"
write(50,*) "	modified:   ../test_gauss_clean/parameters"
write(50,*) ""
write(50,*) "Untracked files:"
write(50,*) "  (use ""git add <file>..."" to include in what will be committed)"
write(50,*) "	../test_gauss_clean/RUNNING"
write(50,*) ""
write(50,*) "no changes added to commit (use ""git add"" and/or ""git commit -a"")"
