write(50,*) "On branch cursor/align-gauss-constraint-implementation-with-paper-claude-4.5-opus-high-thinking-4441"
write(50,*) "Your branch is up to date with 'origin/cursor/align-gauss-constraint-implementation-with-paper-claude-4.5-opus-high-thinking-4441'."
write(50,*) ""
write(50,*) "Changes not staged for commit:"
write(50,*) "  (use ""git add <file>..."" to update what will be committed)"
write(50,*) "  (use ""git restore <file>..."" to discard changes in working directory)"
write(50,*) "	modified:   ALF.out"
write(50,*) "	modified:   Global_mod.o"
write(50,*) "	modified:   Hamiltonian_main_mod.F90"
write(50,*) "	modified:   Hamiltonian_main_mod.o"
write(50,*) "	modified:   Hamiltonians/Hamiltonian_Hubbard_Plain_Vanilla_smod.o"
write(50,*) "	modified:   Hamiltonians/Hamiltonian_Hubbard_smod.o"
write(50,*) "	modified:   Hamiltonians/Hamiltonian_Kondo_smod.o"
write(50,*) "	modified:   Hamiltonians/Hamiltonian_LRC_smod.o"
write(50,*) "	modified:   Hamiltonians/Hamiltonian_Spin_Peierls_smod.o"
write(50,*) "	modified:   Hamiltonians/Hamiltonian_Z2_Matter_smod.F90"
write(50,*) "	modified:   Hamiltonians/Hamiltonian_Z2_Matter_smod.o"
write(50,*) "	modified:   Hamiltonians/Hamiltonian_tV_smod.o"
write(50,*) "	modified:   Langevin_HMC_mod.o"
write(50,*) "	modified:   Wrapgr_mod.o"
write(50,*) "	modified:   git.h"
write(50,*) "	modified:   git_status.h"
write(50,*) "	modified:   global_mod.mod"
write(50,*) "	modified:   hamiltonian_main.mod"
write(50,*) "	modified:   hamiltonian_main.smod"
write(50,*) "	modified:   hamiltonian_main@ham_hubbard_plain_vanilla_smod.smod"
write(50,*) "	modified:   hamiltonian_main@ham_hubbard_smod.smod"
write(50,*) "	modified:   hamiltonian_main@ham_kondo_smod.smod"
write(50,*) "	modified:   hamiltonian_main@ham_lrc_smod.smod"
write(50,*) "	modified:   hamiltonian_main@ham_spin_peierls_smod.smod"
write(50,*) "	modified:   hamiltonian_main@ham_tv_smod.smod"
write(50,*) "	modified:   hamiltonian_main@ham_z2_matter_smod.smod"
write(50,*) "	modified:   hop_mod.mod"
write(50,*) "	modified:   langevin_hmc_mod.mod"
write(50,*) "	modified:   main.F90"
write(50,*) "	modified:   main.o"
write(50,*) "	modified:   predefined_hoppings.mod"
write(50,*) "	modified:   predefined_trial.mod"
write(50,*) "	modified:   tau_m_mod.mod"
write(50,*) "	modified:   tau_m_mod.o"
write(50,*) "	modified:   tau_p_mod.mod"
write(50,*) "	modified:   tau_p_mod.o"
write(50,*) "	modified:   wrapgr_mod.mod"
write(50,*) "	modified:   wrapul_mod.F90"
write(50,*) "	modified:   wrapur_mod.o"
write(50,*) "	modified:   ../test_gauss/Den_eq"
write(50,*) "	modified:   ../test_gauss/Flux_scal"
write(50,*) "	modified:   ../test_gauss/GaussViol_scal"
write(50,*) "	modified:   ../test_gauss/Gauss_scal"
write(50,*) "	modified:   ../test_gauss/Green_eq"
write(50,*) "	modified:   ../test_gauss/Greenf_eq"
write(50,*) "	modified:   ../test_gauss/Part_scal"
write(50,*) "	modified:   ../test_gauss/Q_eq"
write(50,*) "	modified:   ../test_gauss/Q_scal"
write(50,*) "	modified:   ../test_gauss/SpinZ_eq"
write(50,*) "	modified:   ../test_gauss/X_scal"
write(50,*) "	modified:   ../test_gauss/confout_0"
write(50,*) "	modified:   ../test_gauss/info"
write(50,*) "	modified:   ../test_gauss/info_git"
write(50,*) "	modified:   ../test_gauss/parameters"
write(50,*) "	modified:   ../test_gauss/seeds"
write(50,*) ""
write(50,*) "Untracked files:"
write(50,*) "  (use ""git add <file>..."" to include in what will be committed)"
write(50,*) "	../test_gauss/ALF.out"
write(50,*) "	../test_gauss/run.log"
write(50,*) ""
write(50,*) "no changes added to commit (use ""git add"" and/or ""git commit -a"")"
